# Generated by Django 3.2.5 on 2021-10-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osname', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('licence', models.CharField(max_length=100)),
                ('iso', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='serial_no1',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
