# Generated by Django 3.2.5 on 2021-10-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0003_acategory_astatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='acategory',
            name='acid',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='astatus',
            name='asid',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
