# Generated by Django 3.2.5 on 2021-10-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0004_auto_20211030_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lid', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='acategory',
            name='acid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='astatus',
            name='asid',
            field=models.CharField(max_length=100),
        ),
    ]
