# Generated by Django 3.2.5 on 2021-10-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0005_auto_20211030_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='adress',
            field=models.CharField(default='1', max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
