# Generated by Django 3.2.5 on 2021-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0007_auto_20211030_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='ms_office_version',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
