# Generated by Django 3.2.5 on 2021-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0008_ops_ms_office_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ops',
            name='ms_office_version',
            field=models.CharField(max_length=100),
        ),
    ]
