# Generated by Django 3.2.5 on 2021-11-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0012_auto_20211116_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='vegetables',
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='amc_end_date',
            field=models.DateField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='amc_start_date',
            field=models.DateField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='hdd',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='machine_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='make1',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='make2',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='processor_purchase_date',
            field=models.DateField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ram',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='usage_type',
            field=models.CharField(choices=[('Old', 'Old'), ('New', 'New')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_acceptance_date',
            field=models.DateField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_handed_over_date',
            field=models.DateField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='warranty_end_date',
            field=models.DateField(default='1', max_length=100),
        ),
    ]
