# Generated by Django 3.2.5 on 2021-11-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0014_auto_20211116_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='access',
            field=models.BooleanField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='adobe_acrobate',
            field=models.BooleanField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='antivirus',
            field=models.BooleanField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='autocad',
            field=models.BooleanField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='sap',
            field=models.BooleanField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='visio',
            field=models.BooleanField(default='1', max_length=100),
        ),
    ]
