# Generated by Django 3.2.5 on 2021-11-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0016_auto_20211116_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='hdd',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='machine_type',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='make1',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='make2',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ram',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='usage_type',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
