# Generated by Django 3.2.5 on 2021-11-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0017_auto_20211116_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='antivirus',
        ),
    ]
