# Generated by Django 3.2.5 on 2021-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0018_remove_assetmodel_antivirus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='antivirus',
            field=models.BooleanField(default='1'),
        ),
    ]
