# Generated by Django 3.2.9 on 2021-11-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0019_assetmodel_antivirus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetModel',
        ),
    ]
