# Generated by Django 3.2.9 on 2021-11-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0021_assetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='asset_no',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='emp_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='usage_type',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
