# Generated by Django 3.2.9 on 2021-11-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0023_auto_20211119_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='access',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='adobe_acrobate',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='amc_end_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='amc_start_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='antivirus',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='autocad',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='ms_office_version',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='oem',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='os',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='os_version',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='processor_purchase_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='remarks',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='sap',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='user_acceptance_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='user_handed_over_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='visio',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='warranty_end_date',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
