# Generated by Django 3.2.9 on 2021-11-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0024_auto_20211119_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmodel',
            old_name='make2',
            new_name='hdd_make',
        ),
        migrations.RenameField(
            model_name='assetmodel',
            old_name='model',
            new_name='hdd_model',
        ),
        migrations.RenameField(
            model_name='assetmodel',
            old_name='serial_no2',
            new_name='hdd_serial_no',
        ),
        migrations.RenameField(
            model_name='assetmodel',
            old_name='make1',
            new_name='machine_make',
        ),
        migrations.RenameField(
            model_name='assetmodel',
            old_name='serial_no1',
            new_name='machine_serial_no',
        ),
    ]
