# Generated by Django 3.2.9 on 2021-11-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0027_alter_assetmodel_processor_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='processor_purchase_date',
            field=models.DateField(verbose_name='processor_purchase_date'),
        ),
    ]
