# Generated by Django 3.2.9 on 2021-11-19 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0028_alter_assetmodel_processor_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='processor_purchase_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
