# Generated by Django 3.2.9 on 2021-11-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0029_alter_assetmodel_processor_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='access',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='adobe_acrobate',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='amc_end_date',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='amc_start_date',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='antivirus',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='autocad',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='ms_office_version',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='oem',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='os',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='processor_purchase_date',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='sap',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='user_acceptance_date',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='user_handed_over_date',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='visio',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='warranty_end_date',
        ),
    ]
